
#
# prerun.mac
#
#/vis/open OGLIX
/vis/open OGLSX
#/vis/open DAWNFILE
#/vis/open VRML1FILE
#
#
/vis/viewer/reset
#
#/vis/viewer/set/style surface
/vis/viewer/set/style wireframe
#
/vis/viewer/set/viewpointThetaPhi   90.00 0.00
#/vis/viewer/set/viewpointThetaPhi   89.00 90.00
#
/vis/drawVolume 
#/vis/viewer/set/autoRefresh
#
/vis/viewer/zoom 1.0
/tracking/storeTrajectory 1
#/vis/viewer/refresh
#/vis/viewer/flush
/vis/scene/endOfEventAction accumulate
#
#
